public with sharing class CollegeRegistrationDTO {
    public String collegeName { get; set; }
    public String tpoName { get; set; }
    public String collegeTPOEmail { get; set; }
    public String collegeTPOPhone { get; set; }
    public String collegeCode { get; set; }
    public String AffiliatedUniversity { get; set; }
    public String collegeAddress { get; set; }
    public Double zipCode { get; set; }
}